// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDS-y7ERGwcJyvCDJ3bqN_HJbzBPJ6rYM',
    appId: '1:643275765267:android:02aa118afdd49ce4c671e6',
    messagingSenderId: '643275765267',
    projectId: 'dentalintegral-94298',
    storageBucket: 'dentalintegral-94298.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0B8fUcUtCRcRiJ_L4fOeOKJ5EZqm87co',
    appId: '1:643275765267:ios:000cab0e3f537d0ec671e6',
    messagingSenderId: '643275765267',
    projectId: 'dentalintegral-94298',
    storageBucket: 'dentalintegral-94298.firebasestorage.app',
    iosBundleId: 'com.example.temaOscuro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCpUd2QIDyWHpgkZFuJM9oNlw58yBYAMc',
    appId: '1:643275765267:web:de858532ab993e8dc671e6',
    messagingSenderId: '643275765267',
    projectId: 'dentalintegral-94298',
    authDomain: 'dentalintegral-94298.firebaseapp.com',
    storageBucket: 'dentalintegral-94298.firebasestorage.app',
    measurementId: 'G-JMFS0149KT',
  );
}
